ACTIONS = (
    "noop",
    "move_left",
    "move_right",
    "move_up",
    "move_down",
    "do",
    "sleep",
    "place_stone",
    "place_table",
    "place_furnace",
    "place_plant",
    "make_wood_pickaxe",
    "make_stone_pickaxe",
    "make_iron_pickaxe",
    "make_wood_sword",
    "make_stone_sword",
    "make_iron_sword",
)
FACINGS = ("up", "right", "down", "left")
FRONTS = (
    "walkable",
    "water",
    "lava",
    "stone",
    "tree",
    "coal",
    "iron",
    "diamond",
    "table",
    "furnace",
    "cow",
    "zombie",
    "skeleton",
    "plant",
    "arrow",
)
VITALS = ("health", "food", "drink", "energy")
RESOURCES = ("wood", "stone", "coal", "iron")
TOOLS = (
    "wood_pickaxe",
    "stone_pickaxe",
    "iron_pickaxe",
    "wood_sword",
    "stone_sword",
    "iron_sword",
)
ACHIEVEMENTS = (
    "collect_coal",
    "collect_diamond",
    "collect_drink",
    "collect_iron",
    "collect_sapling",
    "collect_stone",
    "collect_wood",
    "defeat_skeleton",
    "defeat_zombie",
    "eat_cow",
    "eat_plant",
    "make_iron_pickaxe",
    "make_iron_sword",
    "make_stone_pickaxe",
    "make_stone_sword",
    "make_wood_pickaxe",
    "make_wood_sword",
    "place_furnace",
    "place_plant",
    "place_stone",
    "place_table",
    "wake_up",
)
